### PR TITLE
Login and Register

### PR DESCRIPTION
**Pull request by AiaRup**
Add login and Register with hooks.
Install libreries.
Add react lazy.
Add language support base.

### CODE REVIEW

**Comment by veroena** [comment]
I'm finally reviewing this after a million and a half years because I'm the worst person that has ever existed!

It throws this error while initializing:
`Error: Your Okta URL must start with https. Current value: undefined/oauth2/default. You can copy your domain from the Okta Developer Console. Follow these instructions to find it: https://bit.ly/finding-okta-domain`

I think I installed everything, am I missing something to make it work?

**Comment by AiaRup** [comment]
> I'm finally reviewing this after a million and a half years because I'm the worst person that has ever existed!
> 
> It throws this error while initializing:
> `Error: Your Okta URL must start with https. Current value: undefined/oauth2/default. You can copy your domain from the Okta Developer Console. Follow these instructions to find it: https://bit.ly/finding-okta-domain`
> 
> I think I installed everything, am I missing something to make it work?

Do you have the `.env` file?

**Comment by veroena** [comment]
Thank you for sending the contents of the .env file! How can we keep up with updating it since it is included in .gitignore?

**Review by veroena — APPROVED** [review]

**Comment by veroena** [comment]
Screenshot from 2020-10-13 13-48-49

It looks like I can't merge without writing access :/

**Comment by AiaRup** [comment]
> Thank you for sending the contents of the .env file! How can we keep up with updating it since it is included in .gitignore?

I guess we can put it in Trello for now? I don't think it is a good practice to put it in the repository..

**Pull request merged**
